rm(list=ls())
library(Seurat)
library(Signac)
library(GenomicRanges)
library(multiomeFate)

load("../../../../out/kevin/Writeup6e/Writeup6e_CIS_peak-entropy.RData")
load("../../../../out/kevin/Writeup6d/Writeup6d_coverage_pileup_CIS.RData")
source("../Writeup6d/coverage_extractor_singlecell.R")
source("../Writeup6d/coverage_extractor_singlecell-plotter.R")
source("../Writeup6d/coverage_pileup.R")
source("../Writeup6d/coverage_pileup_plotter.R")
